Repository QB-Software-swe/docs, pull requests merged in 2023-12, with the labels that each got.

#31 Adr_cartelle
  config.csv
  src/analisi_dei_requisiti/changelog.tex
  src/analisi_dei_requisiti/sections/UC-obbligatori.tex
Labels: documentation, enhancement, AdR

#34 Verbale 2023-11-06
  config.csv
  src/verbali/interni/2023-11-06/Verbale_interno_2023-11-06.tex
  src/verbali/interni/2023-11-06/base.tex
  src/verbali/interni/2023-11-06/changelog.tex
  src/verbali/interni/2023-11-06/imgs/qb-software-logo.png
  src/verbali/interni/2023-11-06/imgs/unipd_logo.png
  src/verbali/interni/2023-11-06/imgs/x.png
Labels: documentation, enhancement, VI

#36 Verbale 2023-11-13
  config.csv
  src/verbali/interni/2023-11-13/Verbale_interno_2023-11-13.tex
  src/verbali/interni/2023-11-13/base.tex
  src/verbali/interni/2023-11-13/changelog.tex
  src/verbali/interni/2023-11-13/imgs/qb-software-logo.png
  src/verbali/interni/2023-11-13/imgs/unipd_logo.png
  src/verbali/interni/2023-11-13/imgs/x.png
Labels: documentation, enhancement, VI

#35 Verbale 2023-11-27
  config.csv
  src/verbali/interni/2023-11-27/Verbale_interno_2023-11-27.tex
  src/verbali/interni/2023-11-27/base.tex
  src/verbali/interni/2023-11-27/changelog.tex
  src/verbali/interni/2023-11-27/imgs/qb-software-logo.png
  src/verbali/interni/2023-11-27/imgs/unipd_logo.png
  src/verbali/interni/2023-11-27/imgs/x.png
Labels: documentation, enhancement, VI

#33 Aggiunti casi d'uso email
  src/analisi_dei_requisiti/changelog.tex
  src/analisi_dei_requisiti/sections/UC-obbligatori.tex
Labels: documentation, enhancement, AdR

#32 Aggiunta sezione su norme organizzative alle Norme di Progetto
  src/norme_di_progetto/Norme_di_progetto.tex
  src/norme_di_progetto/changelog.tex
  src/norme_di_progetto/sections/organizational_processes/documentation.tex
  src/norme_di_progetto/sections/organizational_processes/introduction.tex
Labels: documentation, enhancement, WoW, NdP

#42 PdP- aggiunta pianificazione dettaglio Sprint1
  src/piano_di_progetto/changelog.tex
  src/piano_di_progetto/imgs/sprint1.png
  src/piano_di_progetto/sections/pianificazione.tex
Labels: documentation, enhancement, PdP

#59 Verbale esterno 2023-12-11
  src/verbali/esterni/2023-12-11/Verbale_esterno_2023-12-11.tex
  src/verbali/esterni/2023-12-11/base.tex
  src/verbali/esterni/2023-12-11/changelog.tex
  src/verbali/esterni/2023-12-11/imgs/qb-software-logo.png
  src/verbali/esterni/2023-12-11/imgs/unipd_logo.png
  src/verbali/esterni/2023-12-11/imgs/x.png
Labels: documentation

#55 NdP - stesura processo di fornitura
  src/norme_di_progetto/Norme_di_progetto.tex
  src/norme_di_progetto/changelog.tex
  src/norme_di_progetto/sections/primary_processes/introduction.tex
  src/norme_di_progetto/sections/primary_processes/supply_process.tex
Labels: documentation, enhancement, NdP

#62 Verbale esterno 2023 12 07
  config.csv
  src/verbali/esterni/2023-12-07/Verbale_esterno_2023-12-07.tex
  src/verbali/esterni/2023-12-07/base.tex
  src/verbali/esterni/2023-12-07/changelog.tex
  src/verbali/esterni/2023-12-07/imgs/qb-software-logo.png
  src/verbali/esterni/2023-12-07/imgs/unipd_logo.png
  src/verbali/esterni/2023-12-07/imgs/x.png
Labels: documentation, enhancement, VE

#54 NdP - correzione ed espansione gestione organizzativa
  src/norme_di_progetto/changelog.tex
  src/norme_di_progetto/sections/organizational_processes/documentation.tex
  src/norme_di_progetto/sections/organizational_processes/introduction.tex
  src/norme_di_progetto/sections/organizational_processes/management_process.tex
Labels: documentation, enhancement, NdP

#64 Caricare verbale 2023-11-16
  config.csv
  src/verbali/esterni/2023-11-16/Verbale_esterno_2023-11-16.tex
  src/verbali/esterni/2023-11-16/base.tex
  src/verbali/esterni/2023-11-16/changelog.tex
  src/verbali/esterni/2023-11-16/imgs/qb-software-logo.png
  src/verbali/esterni/2023-11-16/imgs/unipd_logo.png
  src/verbali/esterni/2023-11-16/imgs/x.png
Labels: documentation, enhancement, VE

#65 Fix destination folder
  Candidatura/Documenti_esterni/Verbali/Verbale_esterno_2023-12-07_0.1.0.pdf
  config.csv
Labels: documentation, enhancement, VE

#56 Verbale 2023-12-04
  config.csv
  src/verbali/interni/2023-12-04/Verbale_interno_2023-12-04.tex
  src/verbali/interni/2023-12-04/base.tex
  src/verbali/interni/2023-12-04/changelog.tex
  src/verbali/interni/2023-12-04/imgs/qb-software-logo.png
  src/verbali/interni/2023-12-04/imgs/unipd_logo.png
  src/verbali/interni/2023-12-04/imgs/x.png
Labels: documentation, enhancement, VI

#60 Proseguimento Glossario
  src/glossario/Glossario.tex
  src/glossario/changelog.tex
Labels: documentation, enhancement, Glossario

#66 Fix verbale 2023-12-11
  config.csv
  src/verbali/esterni/2023-12-11/Verbale_esterno_2023-12-11.tex
  src/verbali/interni/2023-12-04/Verbale_interno_2023-12-04.tex
Labels: documentation, enhancement, VI, VE

#73 Prima stesura Piano di Qualifica
  .github/config.csv
  index.html
  src/piano_di_qualifica/base.tex
  src/piano_di_qualifica/changelog.tex
  src/piano_di_qualifica/imgs/qb-software-logo.png
  src/piano_di_qualifica/imgs/unipd_logo.png
  src/piano_di_qualifica/imgs/x.png
  src/piano_di_qualifica/piano_di_qualifica.lot
  src/piano_di_qualifica/piano_di_qualifica.tex
  src/piano_di_qualifica/sections/cruscotto.tex
  src/piano_di_qualifica/sections/intro.tex
  src/piano_di_qualifica/sections/misure.tex
  src/piano_di_qualifica/sections/test.tex
  src/piano_di_qualifica/sections/valutazioni.tex
Labels: documentation, enhancement, PdQ

#76 Verbale interno 2023/12/18
  .github/config.csv
  index.html
  src/verbali/interni/2023-12-18/Verbale_interno_2023-12-18.tex
  src/verbali/interni/2023-12-18/base.tex
  src/verbali/interni/2023-12-18/changelog.tex
  src/verbali/interni/2023-12-18/imgs/qb-software-logo.png
  src/verbali/interni/2023-12-18/imgs/unipd_logo.png
  src/verbali/interni/2023-12-18/imgs/x.png
Labels: documentation, enhancement, VI

#77 Ad r tabella
  src/analisi_dei_requisiti/changelog.tex
  src/analisi_dei_requisiti/sections/requisiti.tex
  src/analisi_dei_requisiti/sections/uc_imgs/UC01.png
  src/analisi_dei_requisiti/sections/uc_imgs/UC03.png
  src/analisi_dei_requisiti/sections/uc_imgs/UC07.png
  src/analisi_dei_requisiti/sections/uc_imgs/UC11.png
  src/analisi_dei_requisiti/sections/uc_imgs/UC12.png
  src/analisi_dei_requisiti/sections/uc_imgs/UC13.png
  src/analisi_dei_requisiti/sections/usecase/UC6.tex
  src/analisi_dei_requisiti/sections/usecase/UC7.tex
  src/analisi_dei_requisiti/sections/usecase/UCS.tex
Labels: documentation, enhancement, AdR
